version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: codegrade_user
      POSTGRES_PASSWORD: passer
      POSTGRES_DB: codegrade
    ports:
      - "5832:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
